/**
 * ESPEN – js/data.js
 * Dados seed: Competências (50), Ações Educativas (5), configurações.
 * Chamado uma única vez por initializeData() em app.js.
 */

/* ── Constantes / listas de referência ──────────────────────── */
const CARGOS = [
  'Agente Penitenciário Federal',
  'Especialista em Assistência Penitenciária',
  'Todos os Cargos',
];

const EIXOS = [
  'Eixo 1 – Gestão Penitenciária',
  'Eixo 2 – Segurança e Custódia',
  'Eixo 3 – Reinserção Social',
  'Eixo 4 – Saúde Penitenciária',
  'Eixo 5 – Gestão de Pessoas',
  'Eixo 6 – Suporte Organizacional',
];

const UNIDADES_TEMATICAS = [
  'Gestão e Governança Pública',
  'Segurança Pública e Penitenciária',
  'Direitos Humanos e Cidadania',
  'Saúde no Sistema Penitenciário',
  'Reinserção e Reintegração Social',
  'Gestão de Pessoas e Competências',
  'Tecnologia da Informação',
  'Inteligência Penitenciária',
  'Legislação e Normativas',
  'Ética e Integridade',
  'Comunicação Institucional',
  'Finanças e Orçamento Público',
  'Logística e Infraestrutura',
  'Educação no Sistema Penitenciário',
  'Trabalho no Sistema Penitenciário',
  'Assistência Jurídica',
  'Assistência Social',
  'Assistência Psicológica',
  'Assistência Religiosa',
  'Controle e Fiscalização',
  'Liderança e Gestão de Equipes',
  'Planejamento Estratégico',
  'Mediação e Resolução de Conflitos',
  'Gestão Ambiental',
  'Relações Internacionais Penitenciárias',
  'Outros',
];

const TIPOLOGIAS_COMPLEXIDADE = ['Básico', 'Intermediário', 'Avançado'];
const TIPOLOGIAS_OBJETIVO = ['Cognitivo', 'Atitudinal', 'Procedimental'];
const MATRIZES = ['2017', '2023', '2026'];
const CATEGORIAS = ['Especialista', 'Geral'];
const MODALIDADES = ['Presencial', 'EaD', 'Semipresencial', 'Híbrido'];
const STATUS_ACAO = ['Planejada', 'Em execução', 'Concluída', 'Cancelada'];
const ESCOLAS = [
  'ESPEN',
  'ENAP',
  'CEI-SENAPPEN',
  'Escola Superior da Magistratura',
  'Parceiro externo',
];
const NIVEIS_ACESSO = ['Administrador', 'Gestor', 'Servidor', 'Visitante'];

/* ── Seed – 50 Competências ─────────────────────────────────── */
const SEED_COMPETENCIAS = [
  // ── Eixo 1 – Gestão Penitenciária (10 registros) ────────────
  {
    id: 'comp-001', competencia: 'Planejamento e execução de políticas penitenciárias',
    categoria: 'Geral', subcategoria: 'Planejamento Institucional',
    cargo: 'Todos os Cargos', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Planejamento Estratégico',
    conhecimentoCritico: 'Fundamentos de administração pública, ciclo de políticas públicas, Plano Nacional de Política Criminal e Penitenciária.',
    objetivoAprendizagem: 'Elaborar e monitorar planos de ação alinhados às diretrizes da política penitenciária nacional.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-002', competencia: 'Gestão de contratos e convênios no sistema penitenciário',
    categoria: 'Especialista', subcategoria: 'Gestão Administrativa',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Finanças e Orçamento Público',
    conhecimentoCritico: 'Lei 14.133/2021 (Nova Lei de Licitações), gestão de contratos públicos, prestação de contas e compliance.',
    objetivoAprendizagem: 'Gerenciar contratos e convênios aplicando a legislação vigente e as boas práticas de controle interno.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-003', competencia: 'Elaboração e acompanhamento orçamentário',
    categoria: 'Especialista', subcategoria: 'Orçamento Público',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Finanças e Orçamento Público',
    conhecimentoCritico: 'LOA, PPA, LDO, SIAFI, execução orçamentária e financeira.',
    objetivoAprendizagem: 'Elaborar peças orçamentárias e acompanhar a execução financeira da unidade.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-004', competencia: 'Governança corporativa em unidades prisionais',
    categoria: 'Geral', subcategoria: 'Governança',
    cargo: 'Todos os Cargos', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Gestão e Governança Pública',
    conhecimentoCritico: 'Princípios de governança pública (TCU), controles internos, accountability e transparência.',
    objetivoAprendizagem: 'Aplicar princípios de boa governança na gestão da unidade prisional.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-005', competencia: 'Gestão da informação e documentação penitenciária',
    categoria: 'Geral', subcategoria: 'Gestão Documental',
    cargo: 'Todos os Cargos', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Tecnologia da Informação',
    conhecimentoCritico: 'Lei de Acesso à Informação, LGPD, sistemas INFOPEN/SISDEPEN, gestão arquivística.',
    objetivoAprendizagem: 'Organizar e gerir documentos e informações prisionais conforme normativas legais.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-006', competencia: 'Planejamento estratégico organizacional',
    categoria: 'Especialista', subcategoria: 'Planejamento Institucional',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Planejamento Estratégico',
    conhecimentoCritico: 'BSC, OKR, metodologias de planejamento estratégico, indicadores de desempenho.',
    objetivoAprendizagem: 'Desenvolver e acompanhar planos estratégicos alinhados à missão da SENAPPEN.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-007', competencia: 'Avaliação e monitoramento de indicadores institucionais',
    categoria: 'Geral', subcategoria: 'Monitoramento e Avaliação',
    cargo: 'Todos os Cargos', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Planejamento Estratégico',
    conhecimentoCritico: 'KPIs, dashboards gerenciais, relatórios de gestão, ciclo PDCA.',
    objetivoAprendizagem: 'Monitorar indicadores de desempenho e propor ações corretivas com base nos resultados.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-008', competencia: 'Elaboração de relatórios gerenciais',
    categoria: 'Geral', subcategoria: 'Comunicação Gerencial',
    cargo: 'Todos os Cargos', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Comunicação Institucional',
    conhecimentoCritico: 'Técnicas de redação oficial, estrutura de relatórios, visualização de dados.',
    objetivoAprendizagem: 'Produzir relatórios gerenciais claros, objetivos e em conformidade com as normas.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-009', competencia: 'Gestão de projetos no setor público',
    categoria: 'Especialista', subcategoria: 'Gestão de Projetos',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Gestão e Governança Pública',
    conhecimentoCritico: 'PMBOK, metodologias ágeis (Scrum/Kanban), escritório de projetos governamental.',
    objetivoAprendizagem: 'Gerenciar projetos com escopo, prazo e custo definidos usando metodologias reconhecidas.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-010', competencia: 'Controle interno e compliance público',
    categoria: 'Especialista', subcategoria: 'Controle e Auditoria',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 1 – Gestão Penitenciária',
    unidadeTematica: 'Controle e Fiscalização',
    conhecimentoCritico: 'COSO, normativas CGU/TCU, programas de integridade, prevenção à corrupção.',
    objetivoAprendizagem: 'Implementar mecanismos de controle interno e programas de integridade na unidade.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },

  // ── Eixo 2 – Segurança e Custódia (10 registros) ────────────
  {
    id: 'comp-011', competencia: 'Procedimentos operacionais de segurança prisional',
    categoria: 'Geral', subcategoria: 'Segurança Operacional',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Segurança Pública e Penitenciária',
    conhecimentoCritico: 'Normas de segurança DEPEN, POPs de custódia, uso progressivo da força.',
    objetivoAprendizagem: 'Executar procedimentos de segurança e custódia conforme normativas federais.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-012', competencia: 'Gestão de crises e incidentes prisionais',
    categoria: 'Geral', subcategoria: 'Gestão de Crises',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Segurança Pública e Penitenciária',
    conhecimentoCritico: 'Planos de contingência, negociação em situações de crise, Resolução CNPCP.',
    objetivoAprendizagem: 'Coordenar respostas a crises e incidentes prisionais minimizando riscos à vida.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-013', competencia: 'Inteligência penitenciária e análise de risco',
    categoria: 'Especialista', subcategoria: 'Inteligência',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Inteligência Penitenciária',
    conhecimentoCritico: 'Fundamentos de inteligência, análise criminal, RINTEP, sigilo de informações.',
    objetivoAprendizagem: 'Produzir informes e relatórios de inteligência para suporte à tomada de decisão.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-014', competencia: 'Uso da força e técnicas de imobilização',
    categoria: 'Geral', subcategoria: 'Técnicas Operacionais',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Segurança Pública e Penitenciária',
    conhecimentoCritico: 'Matriz de uso progressivo da força, técnicas de imobilização, primeiros socorros.',
    objetivoAprendizagem: 'Aplicar técnicas de contenção e uso da força de forma proporcional e legal.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-015', competencia: 'Escolta e condução de presos',
    categoria: 'Geral', subcategoria: 'Segurança Operacional',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Segurança Pública e Penitenciária',
    conhecimentoCritico: 'Protocolos de escolta, legislação pertinente, planejamento de rota, segurança em deslocamento.',
    objetivoAprendizagem: 'Executar escoltas com segurança cumprindo todos os procedimentos estabelecidos.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },
  {
    id: 'comp-016', competencia: 'Controle e monitoramento eletrônico de presos',
    categoria: 'Geral', subcategoria: 'Tecnologia de Custódia',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Tecnologia da Informação',
    conhecimentoCritico: 'Sistemas de monitoramento eletrônico, tornozeleiras, geofencing, Res. CNJ 412/2021.',
    objetivoAprendizagem: 'Operar sistemas de monitoramento eletrônico e identificar violações de acordo.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-017', competencia: 'Classificação e individualização da pena',
    categoria: 'Especialista', subcategoria: 'Execução Penal',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Legislação e Normativas',
    conhecimentoCritico: 'Lei de Execução Penal (LEP), Resolução 1/1988 CNPCP, PCPA, laudos técnicos.',
    objetivoAprendizagem: 'Elaborar laudos de classificação prisional e individualizar o tratamento penal.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-018', competencia: 'Prevenção e gestão de rebeliões',
    categoria: 'Geral', subcategoria: 'Gestão de Crises',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Segurança Pública e Penitenciária',
    conhecimentoCritico: 'Indicadores de risco, mediação de conflitos, planejamento preventivo.',
    objetivoAprendizagem: 'Identificar sinais de tensão e adotar medidas preventivas para evitar rebeliões.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-019', competencia: 'Primeiros socorros e emergências no cárcere',
    categoria: 'Geral', subcategoria: 'Saúde e Segurança',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'Técnicas de primeiros socorros, RCP, reconhecimento de emergências médicas.',
    objetivoAprendizagem: 'Prestar primeiros socorros em situações de emergência até chegada de equipe especializada.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },
  {
    id: 'comp-020', competencia: 'Análise e prevenção de fugas',
    categoria: 'Geral', subcategoria: 'Segurança Operacional',
    cargo: 'Agente Penitenciário Federal', eixo: 'Eixo 2 – Segurança e Custódia',
    unidadeTematica: 'Segurança Pública e Penitenciária',
    conhecimentoCritico: 'Análise de vulnerabilidades, inspeções de segurança, sistemas de contenção.',
    objetivoAprendizagem: 'Identificar vulnerabilidades estruturais e operacionais para prevenção de fugas.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },

  // ── Eixo 3 – Reinserção Social (8 registros) ────────────────
  {
    id: 'comp-021', competencia: 'Elaboração e execução de programas de reintegração social',
    categoria: 'Especialista', subcategoria: 'Programas Sociais',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Reinserção e Reintegração Social',
    conhecimentoCritico: 'Programas de trabalho e educação prisional, PEESP, Pró-Egresso.',
    objetivoAprendizagem: 'Planejar e executar programas de reintegração social que reduzam a reincidência.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-022', competencia: 'Educação e profissionalização no sistema prisional',
    categoria: 'Geral', subcategoria: 'Educação Prisional',
    cargo: 'Todos os Cargos', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Educação no Sistema Penitenciário',
    conhecimentoCritico: 'PEESP, remição de pena pela educação, EJA, parcerias com MEC/SETEC.',
    objetivoAprendizagem: 'Implementar e apoiar programas educacionais e de qualificação profissional nos presídios.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-023', competencia: 'Gestão do trabalho prisional',
    categoria: 'Especialista', subcategoria: 'Trabalho Prisional',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Trabalho no Sistema Penitenciário',
    conhecimentoCritico: 'Fundamentos do trabalho prisional, remição, regulamentação, cooperativas prisionais.',
    objetivoAprendizagem: 'Gerenciar programas de trabalho prisional garantindo legalidade e benefícios ao preso.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-024', competencia: 'Assistência social ao preso e egresso',
    categoria: 'Especialista', subcategoria: 'Assistência Social',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Assistência Social',
    conhecimentoCritico: 'Serviço social penitenciário, SUAS, políticas de proteção social, acolhimento de egressos.',
    objetivoAprendizagem: 'Realizar atendimento social a presos e egressos promovendo a reinserção comunitária.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-025', competencia: 'Atendimento psicológico no contexto prisional',
    categoria: 'Especialista', subcategoria: 'Assistência Psicológica',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Assistência Psicológica',
    conhecimentoCritico: 'Psicologia jurídica, avaliação psicológica forense, saúde mental no cárcere.',
    objetivoAprendizagem: 'Realizar avaliação e acompanhamento psicológico promovendo saúde mental e reinserção.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-026', competencia: 'Assistência jurídica ao preso',
    categoria: 'Especialista', subcategoria: 'Assistência Jurídica',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Assistência Jurídica',
    conhecimentoCritico: 'LEP, direitos do preso, Defensoria Pública, benefícios legais (progressão, livramento).',
    objetivoAprendizagem: 'Orientar presos sobre seus direitos e facilitar acesso à assistência jurídica.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-027', competencia: 'Mediação de conflitos no ambiente prisional',
    categoria: 'Geral', subcategoria: 'Resolução de Conflitos',
    cargo: 'Todos os Cargos', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Mediação e Resolução de Conflitos',
    conhecimentoCritico: 'Técnicas de mediação, comunicação não-violenta, justiça restaurativa.',
    objetivoAprendizagem: 'Mediar conflitos entre presos e entre presos e funcionários de forma construtiva.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-028', competencia: 'Assistência religiosa e apoio espiritual',
    categoria: 'Geral', subcategoria: 'Assistência Religiosa',
    cargo: 'Todos os Cargos', eixo: 'Eixo 3 – Reinserção Social',
    unidadeTematica: 'Assistência Religiosa',
    conhecimentoCritico: 'Direito à assistência religiosa (LEP art. 24), pluralidade religiosa, protocolos de acesso.',
    objetivoAprendizagem: 'Garantir o acesso à assistência religiosa respeitando a diversidade de crenças.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },

  // ── Eixo 4 – Saúde Penitenciária (7 registros) ──────────────
  {
    id: 'comp-029', competencia: 'Atenção básica à saúde no sistema penitenciário',
    categoria: 'Especialista', subcategoria: 'Saúde Básica',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'PNSSP, PNAISP, UBSp, protocolos clínicos no cárcere.',
    objetivoAprendizagem: 'Coordenar ações de atenção básica à saúde conforme diretrizes do PNAISP.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-030', competencia: 'Prevenção e controle de doenças infectocontagiosas',
    categoria: 'Geral', subcategoria: 'Vigilância Epidemiológica',
    cargo: 'Todos os Cargos', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'HIV/AIDS, tuberculose, hepatites, COVID-19, protocolos de isolamento e EPIs.',
    objetivoAprendizagem: 'Aplicar medidas preventivas e de controle para doenças infectocontagiosas no cárcere.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-031', competencia: 'Saúde mental e tratamento de dependência química',
    categoria: 'Especialista', subcategoria: 'Saúde Mental',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'RAPS, CAPS, tratamento de dependência química, Reforma Psiquiátrica, Portaria 482/2014.',
    objetivoAprendizagem: 'Identificar e encaminhar casos de transtornos mentais e dependência química.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-032', competencia: 'Gestão de farmácia e medicamentos no cárcere',
    categoria: 'Especialista', subcategoria: 'Gestão Farmacêutica',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'Assistência farmacêutica, REMUME, controle de psicotrópicos, ANVISA.',
    objetivoAprendizagem: 'Gerenciar o estoque e a dispensação de medicamentos de acordo com normas sanitárias.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-033', competencia: 'Saúde da mulher no sistema penitenciário',
    categoria: 'Especialista', subcategoria: 'Saúde da Mulher',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'Direitos reprodutivos, pré-natal no cárcere, amamentação, saúde mental materna.',
    objetivoAprendizagem: 'Garantir atenção integral à saúde da mulher presa, incluindo gestantes e lactantes.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-034', competencia: 'Vigilância sanitária e ambiental nos estabelecimentos penais',
    categoria: 'Geral', subcategoria: 'Vigilância Sanitária',
    cargo: 'Todos os Cargos', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Gestão Ambiental',
    conhecimentoCritico: 'Normas sanitárias, tratamento de resíduos, controle de vetores, higiene alimentar.',
    objetivoAprendizagem: 'Fiscalizar condições sanitárias e ambientais garantindo a saúde da população carcerária.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },
  {
    id: 'comp-035', competencia: 'Atenção à saúde do servidor penitenciário',
    categoria: 'Especialista', subcategoria: 'Saúde Ocupacional',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 4 – Saúde Penitenciária',
    unidadeTematica: 'Saúde no Sistema Penitenciário',
    conhecimentoCritico: 'Saúde ocupacional, NR-32, estresse pós-traumático, qualidade de vida no trabalho.',
    objetivoAprendizagem: 'Promover ações de saúde e qualidade de vida para servidores do sistema penitenciário.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },

  // ── Eixo 5 – Gestão de Pessoas (8 registros) ────────────────
  {
    id: 'comp-036', competencia: 'Gestão por competências no setor público',
    categoria: 'Especialista', subcategoria: 'Gestão de Competências',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Gestão de Pessoas e Competências',
    conhecimentoCritico: 'Decreto 9.991/2019, PDP, PNDP, CHA (conhecimentos, habilidades, atitudes).',
    objetivoAprendizagem: 'Implementar e coordenar ciclos de gestão por competências conforme Decreto 9.991.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-037', competencia: 'Avaliação de desempenho funcional',
    categoria: 'Geral', subcategoria: 'Avaliação de Desempenho',
    cargo: 'Todos os Cargos', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Gestão de Pessoas e Competências',
    conhecimentoCritico: 'Métodos de avaliação (360°, SMART), feedback, gestão do desempenho.',
    objetivoAprendizagem: 'Conduzir avaliações de desempenho de forma justa e promover o desenvolvimento do servidor.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-038', competencia: 'Liderança e gestão de equipes no ambiente prisional',
    categoria: 'Geral', subcategoria: 'Liderança',
    cargo: 'Todos os Cargos', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Liderança e Gestão de Equipes',
    conhecimentoCritico: 'Estilos de liderança, motivação de equipes, comunicação assertiva, gestão de conflitos.',
    objetivoAprendizagem: 'Exercer liderança situacional promovendo clima organizacional saudável e produtivo.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-039', competencia: 'Elaboração e execução do Plano de Desenvolvimento Individual (PDI)',
    categoria: 'Geral', subcategoria: 'Desenvolvimento de Pessoal',
    cargo: 'Todos os Cargos', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Gestão de Pessoas e Competências',
    conhecimentoCritico: 'Decreto 9.991/2019, mapeamento de lacunas de competência, trilhas de aprendizagem.',
    objetivoAprendizagem: 'Elaborar e acompanhar o PDI alinhando necessidades individuais às metas institucionais.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-040', competencia: 'Gestão do clima organizacional',
    categoria: 'Especialista', subcategoria: 'Clima Organizacional',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Gestão de Pessoas e Competências',
    conhecimentoCritico: 'Pesquisa de clima, cultura organizacional, engajamento, diagnóstico organizacional.',
    objetivoAprendizagem: 'Realizar diagnóstico de clima organizacional e propor ações de melhoria.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-041', competencia: 'Recrutamento e seleção no serviço público',
    categoria: 'Especialista', subcategoria: 'Recrutamento e Seleção',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Gestão de Pessoas e Competências',
    conhecimentoCritico: 'Concurso público, lei 8.112/90, processo seletivo interno, entrevistas por competências.',
    objetivoAprendizagem: 'Conduzir processos de recrutamento e seleção baseados em competências.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-042', competencia: 'Ética e conduta no serviço público',
    categoria: 'Geral', subcategoria: 'Ética Profissional',
    cargo: 'Todos os Cargos', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Ética e Integridade',
    conhecimentoCritico: 'Decreto 1.171/94 (Código de Ética), lei anticorrupção, responsabilidade do servidor.',
    objetivoAprendizagem: 'Pautar suas ações pelos princípios éticos e legais do serviço público.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },
  {
    id: 'comp-043', competencia: 'Comunicação interpessoal e institucional',
    categoria: 'Geral', subcategoria: 'Comunicação',
    cargo: 'Todos os Cargos', eixo: 'Eixo 5 – Gestão de Pessoas',
    unidadeTematica: 'Comunicação Institucional',
    conhecimentoCritico: 'Comunicação não-violenta, redação oficial, oratória, escuta ativa.',
    objetivoAprendizagem: 'Comunicar-se com clareza e assertividade nos ambientes interpessoal e institucional.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },

  // ── Eixo 6 – Suporte Organizacional (7 registros) ────────────
  {
    id: 'comp-044', competencia: 'Tecnologia da informação aplicada ao sistema penitenciário',
    categoria: 'Geral', subcategoria: 'TI Aplicada',
    cargo: 'Todos os Cargos', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Tecnologia da Informação',
    conhecimentoCritico: 'SISDEPEN, INFOPEN, BrVault, SIGEPE, pacote Office, segurança da informação.',
    objetivoAprendizagem: 'Utilizar os sistemas informatizados do órgão com proficiência para gestão de dados.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-045', competencia: 'Proteção de dados pessoais (LGPD) no contexto penitenciário',
    categoria: 'Geral', subcategoria: 'LGPD',
    cargo: 'Todos os Cargos', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Tecnologia da Informação',
    conhecimentoCritico: 'Lei 13.709/2018 (LGPD), dados sensíveis, encarregado de dados, ANPD.',
    objetivoAprendizagem: 'Tratar dados pessoais de presos e servidores em conformidade com a LGPD.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-046', competencia: 'Logística e gestão de materiais penitenciários',
    categoria: 'Geral', subcategoria: 'Logística',
    cargo: 'Todos os Cargos', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Logística e Infraestrutura',
    conhecimentoCritico: 'Gestão de estoque, SIADS, compras governamentais, almoxarifado.',
    objetivoAprendizagem: 'Gerenciar materiais e suprimentos garantindo disponibilidade e controle de estoque.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-047', competencia: 'Gestão de infraestrutura e obras penitenciárias',
    categoria: 'Especialista', subcategoria: 'Infraestrutura',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Logística e Infraestrutura',
    conhecimentoCritico: 'Normas CNPCP sobre capacidade prisional, ABNT, gestão de obras públicas.',
    objetivoAprendizagem: 'Supervisionar projetos e obras de infraestrutura penitenciária conforme normas técnicas.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2023',
  },
  {
    id: 'comp-048', competencia: 'Direitos humanos e dignidade da pessoa presa',
    categoria: 'Geral', subcategoria: 'Direitos Humanos',
    cargo: 'Todos os Cargos', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Direitos Humanos e Cidadania',
    conhecimentoCritico: 'Regras de Mandela, CIDH, Convenção contra Tortura, Lei 9.455/97.',
    objetivoAprendizagem: 'Respeitar e fazer cumprir os direitos humanos da população carcerária.',
    tipologiaObjetivo: 'Atitudinal', tipologiaComplexidade: 'Básico',
    matrizReferencia: '2017',
  },
  {
    id: 'comp-049', competencia: 'Interseccionalidade e diversidade no sistema prisional',
    categoria: 'Geral', subcategoria: 'Diversidade',
    cargo: 'Todos os Cargos', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Direitos Humanos e Cidadania',
    conhecimentoCritico: 'Teoria da interseccionalidade, gênero, raça, LGBTQIA+, população indígena.',
    objetivoAprendizagem: 'Aplicar abordagem interseccional no atendimento à população prisional diversa.',
    tipologiaObjetivo: 'Cognitivo', tipologiaComplexidade: 'Intermediário',
    matrizReferencia: '2026',
  },
  {
    id: 'comp-050', competencia: 'Relações federativas e cooperação interinstitucional',
    categoria: 'Especialista', subcategoria: 'Relações Institucionais',
    cargo: 'Especialista em Assistência Penitenciária', eixo: 'Eixo 6 – Suporte Organizacional',
    unidadeTematica: 'Relações Internacionais Penitenciárias',
    conhecimentoCritico: 'Federalismo, acordos de cooperação, INFOSEG, articulação com estados e municípios.',
    objetivoAprendizagem: 'Articular ações de cooperação com órgãos federais, estaduais e parceiros internacionais.',
    tipologiaObjetivo: 'Procedimental', tipologiaComplexidade: 'Avançado',
    matrizReferencia: '2026',
  },
];

/* ── Seed – 5 Ações Educativas ──────────────────────────────── */
const SEED_ACOES = [
  {
    id: 'acao-001',
    codigo: 'ESPEN-2024-001',
    nome: 'III Curso de Interseccionalidade e Sistema Penitenciário',
    tipo: 'Curso',
    modalidade: 'EaD',
    areaDemandante: 'DIRPP/SENAPPEN',
    escolaProponente: 'ESPEN',
    eixo: 'Eixo 6 – Suporte Organizacional',
    areaTematica: 'Direitos Humanos e Cidadania',
    status: 'Em execução',
    numModulos: 4,
    cargaHoraria: 40,
    publicoAlvo: 'Todos os Cargos',
    vagas: 200,
    descricao: 'Curso de formação que aborda a teoria da interseccionalidade aplicada ao contexto do sistema penitenciário brasileiro, com foco em raça, gênero, classe e orientação sexual.',
    ementa: 'Módulo 1: Fundamentos da interseccionalidade; Módulo 2: Gênero e raça no cárcere; Módulo 3: LGBTQIA+ no sistema penitenciário; Módulo 4: Práticas institucionais inclusivas.',
    metodologia: 'Ensino a distância via plataforma Moodle/ESPEN com videoaulas, fóruns de debate, estudos de caso e avaliação final.',
    objetivoGeral: 'Capacitar servidores do DEPEN para aplicar perspectiva interseccional nas práticas institucionais cotidianas.',
    periodo: '01/03/2024 – 30/04/2024',
    local: 'Plataforma EaD ESPEN',
    instrutor: 'Equipe docente ESPEN/Consultores',
    certificacao: 'Certificado de conclusão 40h – ESPEN/SENAPPEN',
    competenciasVinculadas: ['comp-049', 'comp-048'],
    createdAt: new Date('2024-01-15').getTime(),
    updatedAt: new Date('2024-01-15').getTime(),
  },
  {
    id: 'acao-002',
    codigo: 'ESPEN-2024-002',
    nome: 'VI Curso de Gestão de Fontes Humanas de Informação',
    tipo: 'Curso',
    modalidade: 'Presencial',
    areaDemandante: 'DIAISE/SENAPPEN',
    escolaProponente: 'ESPEN',
    eixo: 'Eixo 2 – Segurança e Custódia',
    areaTematica: 'Inteligência Penitenciária',
    status: 'Concluída',
    numModulos: 5,
    cargaHoraria: 80,
    publicoAlvo: 'Agente Penitenciário Federal',
    vagas: 30,
    descricao: 'Curso especializado em técnicas de gestão de fontes humanas de informação para o contexto da inteligência penitenciária federal.',
    ementa: 'Módulo 1: Fundamentos de inteligência; Módulo 2: Recrutamento e gestão de fontes; Módulo 3: Análise e processamento; Módulo 4: Proteção de fontes; Módulo 5: Aspectos legais.',
    metodologia: 'Aulas expositivas, simulações práticas, análise de casos reais (anonimizados), grupos de trabalho.',
    objetivoGeral: 'Formar agentes capacitados para gestão de fontes humanas de informação no sistema penitenciário federal.',
    periodo: '10/06/2023 – 28/07/2023',
    local: 'ESPEN – Brasília/DF',
    instrutor: 'Especialistas em Inteligência – ABIN/SENAPPEN',
    certificacao: 'Certificado de especialização 80h – ESPEN/SENAPPEN',
    competenciasVinculadas: ['comp-013', 'comp-012'],
    createdAt: new Date('2023-04-10').getTime(),
    updatedAt: new Date('2023-04-10').getTime(),
  },
  {
    id: 'acao-003',
    codigo: 'ESPEN-2024-003',
    nome: 'Formação em Gestão por Competências no DEPEN – Ciclo 2024',
    tipo: 'Programa',
    modalidade: 'Híbrido',
    areaDemandante: 'CGEP/SENAPPEN',
    escolaProponente: 'ESPEN',
    eixo: 'Eixo 5 – Gestão de Pessoas',
    areaTematica: 'Gestão de Pessoas e Competências',
    status: 'Planejada',
    numModulos: 6,
    cargaHoraria: 120,
    publicoAlvo: 'Especialista em Assistência Penitenciária',
    vagas: 50,
    descricao: 'Programa estruturado de formação para implantação do ciclo de Gestão por Competências no DEPEN, abrangendo mapeamento, avaliação e desenvolvimento de competências.',
    ementa: 'Módulo 1: Bases conceituais da GpC; Módulo 2: Decreto 9.991/2019; Módulo 3: Mapeamento de competências; Módulo 4: Avaliação e diagnóstico; Módulo 5: PDI e Trilhas; Módulo 6: Indicadores de resultado.',
    metodologia: 'Encontros presenciais mensais + atividades EaD, coaching, projeto de implementação.',
    objetivoGeral: 'Habilitar gestores para conduzir o processo de gestão por competências em suas unidades.',
    periodo: '01/07/2024 – 15/12/2024',
    local: 'Presencial: ESPEN Brasília | EaD: Plataforma ESPEN',
    instrutor: 'Equipe CGEP/SENAPPEN + consultores ENAP',
    certificacao: 'Certificado de conclusão 120h – ESPEN/SENAPPEN',
    competenciasVinculadas: ['comp-036', 'comp-039', 'comp-037'],
    createdAt: new Date('2024-02-20').getTime(),
    updatedAt: new Date('2024-02-20').getTime(),
  },
  {
    id: 'acao-004',
    codigo: 'ESPEN-2023-004',
    nome: 'Curso de Atualização em Saúde Penitenciária – PNAISP',
    tipo: 'Curso',
    modalidade: 'EaD',
    areaDemandante: 'DIASP/SENAPPEN',
    escolaProponente: 'ESPEN',
    eixo: 'Eixo 4 – Saúde Penitenciária',
    areaTematica: 'Saúde no Sistema Penitenciário',
    status: 'Concluída',
    numModulos: 3,
    cargaHoraria: 30,
    publicoAlvo: 'Especialista em Assistência Penitenciária',
    vagas: 300,
    descricao: 'Curso de atualização sobre a Política Nacional de Atenção Integral à Saúde das Pessoas Privadas de Liberdade no Sistema Prisional (PNAISP).',
    ementa: 'Módulo 1: Fundamentos do PNAISP; Módulo 2: Doenças prevalentes e protocolos; Módulo 3: Gestão da saúde nas unidades prisionais.',
    metodologia: 'EaD auto-instrucional com videoaulas e avaliação online.',
    objetivoGeral: 'Atualizar profissionais de saúde do sistema penitenciário quanto às diretrizes e protocolos do PNAISP.',
    periodo: '01/09/2023 – 31/10/2023',
    local: 'Plataforma EaD ESPEN',
    instrutor: 'Equipe DIASP/SENAPPEN + Ministério da Saúde',
    certificacao: 'Certificado de atualização 30h – ESPEN/SENAPPEN',
    competenciasVinculadas: ['comp-029', 'comp-030', 'comp-031'],
    createdAt: new Date('2023-06-15').getTime(),
    updatedAt: new Date('2023-06-15').getTime(),
  },
  {
    id: 'acao-005',
    codigo: 'ESPEN-2024-005',
    nome: 'Workshop de Ética, Integridade e Prevenção à Corrupção',
    tipo: 'Workshop',
    modalidade: 'Presencial',
    areaDemandante: 'CGU/SENAPPEN',
    escolaProponente: 'ESPEN',
    eixo: 'Eixo 5 – Gestão de Pessoas',
    areaTematica: 'Ética e Integridade',
    status: 'Planejada',
    numModulos: 2,
    cargaHoraria: 16,
    publicoAlvo: 'Todos os Cargos',
    vagas: 80,
    descricao: 'Workshop intensivo sobre ética no serviço público, programas de integridade e prevenção à corrupção no sistema penitenciário.',
    ementa: 'Dia 1: Fundamentos éticos, Código de Ética do servidor, casos práticos; Dia 2: Programa de Integridade, CGFAP, denúncias e proteção ao denunciante.',
    metodologia: 'Debates em grupo, estudos de caso, role-playing.',
    objetivoGeral: 'Sensibilizar e capacitar servidores para práticas éticas e íntegras no exercício da função pública.',
    periodo: '14/08/2024 – 15/08/2024',
    local: 'ESPEN – Brasília/DF',
    instrutor: 'CGU + Comissão de Ética SENAPPEN',
    certificacao: 'Certificado de participação 16h – ESPEN/SENAPPEN',
    competenciasVinculadas: ['comp-042', 'comp-010'],
    createdAt: new Date('2024-03-01').getTime(),
    updatedAt: new Date('2024-03-01').getTime(),
  },
];

/* ── Exporta para uso em outros módulos ─────────────────────── */
window.ESPEN_DATA = {
  CARGOS,
  EIXOS,
  UNIDADES_TEMATICAS,
  TIPOLOGIAS_COMPLEXIDADE,
  TIPOLOGIAS_OBJETIVO,
  MATRIZES,
  CATEGORIAS,
  MODALIDADES,
  STATUS_ACAO,
  ESCOLAS,
  NIVEIS_ACESSO,
  SEED_COMPETENCIAS,
  SEED_ACOES,
};
